general:
  debug: false
  instance_name: "SearXNG"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true

search:
  safe_search: 0
  autocomplete: ""
  autocomplete_min: 4
  favicon_resolver: ""
  default_lang: "auto"
  ban_time_on_fail: 30
  max_ban_time_on_fail: 300
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  base_url: false
  secret_key: "jeeves-searxng-private-instance"
  limiter: false
  public_instance: false
  image_proxy: false
  http_protocol_version: "1.0"
  method: "GET"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

brand: {}

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  doai.io: 'https://dissem.in/'
  sci-hub.se: 'https://sci-hub.se/'

default_doi_resolver: 'oadoi.org'

valkey:
  url: false

ui:
  static_path: ""
  templates_path: ""
  query_in_title: false
  default_theme: simple
  center_alignment: false
  default_locale: ""
  search_on_category_select: true
  hotkeys: default
  url_formatting: pretty
  theme_args:
    simple_style: auto

outgoing:
  request_timeout: 6.0
  max_request_timeout: 15.0
  useragent_suffix: ""
  pool_connections: 20
  pool_maxsize: 10
  keepalive_expiry: 10.0
  enable_http2: true
  retries: 1
  max_redirects: 10

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: true
  searx.plugins.time_zone.SXNGPlugin:
    active: true
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
  searx.plugins.infinite_scroll.SXNGPlugin:
    active: false
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: false
  searx.plugins.tor_check.SXNGPlugin:
    active: false

engines:

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false
    time_range_support: true
    paging: true

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: wikidata
    engine: wikidata
    shortcut: wd
    timeout: 3.0
    weight: 2
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false

  - name: stackoverflow
    engine: stackexchange
    shortcut: st
    api_site: "stackoverflow"
    categories: [it, q&a]
    disabled: false

  - name: google
    engine: google
    shortcut: go
    disabled: true

  - name: google images
    engine: google_images
    shortcut: goi
    disabled: true

  - name: google news
    engine: google_news
    shortcut: gon
    disabled: true

  - name: google videos
    engine: google_videos
    shortcut: gov
    disabled: true

  - name: google scholar
    engine: google_scholar
    shortcut: gos
    disabled: true

  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: true

  - name: qwant
    engine: qwant
    qwant_categ: web
    shortcut: qw
    disabled: true

  - name: yandex
    engine: yandex
    shortcut: yd
    disabled: true
